In [45]:
import pysd
import numpy as np
import xarray as xr
import pandas as pd


In [46]:
# Ignore a pandas warning
import warnings
warnings.simplefilter(action='ignore', category=np.VisibleDeprecationWarning)

In [47]:
# Generate the subscripted models
pysd.read_vensim('/home/lionel/Projects/pysimgame/trials/subscripting_usage/subscript.mdl')
pysd.read_vensim('/home/lionel/Projects/pysimgame/trials/subscripting_usage/teacup.mdl')

In [48]:
model = pysd.load('/home/lionel/Projects/pysimgame/trials/subscripting_usage/teacup.py')
model_subscripted = pysd.load('/home/lionel/Projects/pysimgame/trials/subscripting_usage/teacup_subscript.py')

In [49]:
model, model_subscripted

(<pysd.py_backend.model.Model at 0x7eff1e71dc60>,
 <pysd.py_backend.model.Model at 0x7eff1e702f50>)

In [50]:
model._namespace, model_subscripted._namespace

({'Time': 'time',
  'FINAL TIME': 'final_time',
  'INITIAL TIME': 'initial_time',
  'SAVEPER': 'saveper',
  'TIME STEP': 'time_step',
  'Characteristic Time': 'characteristic_time',
  'Heat Loss to Room': 'heat_loss_to_room',
  'Room Temperature': 'room_temperature',
  'Teacup Temperature': 'teacup_temperature'},
 {'Time': 'time',
  'FINAL TIME': 'final_time',
  'INITIAL TIME': 'initial_time',
  'SAVEPER': 'saveper',
  'TIME STEP': 'time_step',
  'Characteristic Time': 'characteristic_time',
  'Heat Loss to Room': 'heat_loss_to_room',
  'Room Temperature': 'room_temperature',
  'Teacup Temperature': 'teacup_temperature'})

In [51]:
model['Teacup Temperature'], model_subscripted['Teacup Temperature']

(180,
 <xarray.DataArray (teatype: 4)>
 array([ 70,  80,  90, 100])
 Coordinates:
   * teatype  (teatype) <U7 'Mint' 'Green' 'Berries' 'Black')

In [52]:
model.run()

FINAL TIME  INITIAL TIME  SAVEPER  TIME STEP  Characteristic Time  \
0.000           30             0    0.125      0.125                   10   
0.125           30             0    0.125      0.125                   10   
0.250           30             0    0.125      0.125                   10   
0.375           30             0    0.125      0.125                   10   
0.500           30             0    0.125      0.125                   10   
...            ...           ...      ...        ...                  ...   
29.500          30             0    0.125      0.125                   10   
29.625          30             0    0.125      0.125                   10   
29.750          30             0    0.125      0.125                   10   
29.875          30             0    0.125      0.125                   10   
30.000          30             0    0.125      0.125                   10   

        Heat Loss to Room  Room Temperature  Teacup Temperature  
0.000           11.000000                70          180.000000  
0.125           10.862500                70          178.625000  
0.250           10.726719                70          177.267188  
0.375           10.592635                70          175.926348  
0.500           10.460227                70          174.602268  
...                   ...               ...                 ...  
29.500           0.565131                70           75.651312  
29.625           0.558067                70           75.580671  
29.750           0.551091                70           75.510912  
29.875           0.544203                70           75.442026  
30.000           0.537400                70           75.374001  

[241 rows x 8 columns]

In [53]:
model_subscripted.run()

FINAL TIME  INITIAL TIME  SAVEPER  TIME STEP  Characteristic Time  \
0.000           30             0    0.125      0.125                   10   
0.125           30             0    0.125      0.125                   10   
0.250           30             0    0.125      0.125                   10   
0.375           30             0    0.125      0.125                   10   
0.500           30             0    0.125      0.125                   10   
...            ...           ...      ...        ...                  ...   
29.500          30             0    0.125      0.125                   10   
29.625          30             0    0.125      0.125                   10   
29.750          30             0    0.125      0.125                   10   
29.875          30             0    0.125      0.125                   10   
30.000          30             0    0.125      0.125                   10   

        Heat Loss to Room[Mint]  Heat Loss to Room[Green]  \
0.000                  5.000000                  6.000000   
0.125                  4.937500                  5.925000   
0.250                  4.875781                  5.850938   
0.375                  4.814834                  5.777801   
0.500                  4.754649                  5.705578   
...                         ...                       ...   
29.500                 0.256878                  0.308253   
29.625                 0.253667                  0.304400   
29.750                 0.250496                  0.300595   
29.875                 0.247365                  0.296838   
30.000                 0.244273                  0.293127   

        Heat Loss to Room[Berries]  Heat Loss to Room[Black]  \
0.000                     7.000000                  8.000000   
0.125                     6.912500                  7.900000   
0.250                     6.826094                  7.801250   
0.375                     6.740768                  7.703734   
0.500                     6.656508                  7.607438   
...                            ...                       ...   
29.500                    0.359629                  0.411005   
29.625                    0.355134                  0.405867   
29.750                    0.350694                  0.400794   
29.875                    0.346311                  0.395784   
30.000                    0.341982                  0.390836   

        Room Temperature  Teacup Temperature[Mint]  Teacup Temperature[Green]  \
0.000                 20                 70.000000                  80.000000   
0.125                 20                 69.375000                  79.250000   
0.250                 20                 68.757812                  78.509375   
0.375                 20                 68.148340                  77.778008   
0.500                 20                 67.546486                  77.055783   
...                  ...                       ...                        ...   
29.500                20                 22.568778                  23.082534   
29.625                20                 22.536669                  23.044002   
29.750                20                 22.504960                  23.005952   
29.875                20                 22.473648                  22.968378   
30.000                20                 22.442728                  22.931273   

        Teacup Temperature[Berries]  Teacup Temperature[Black]  
0.000                     90.000000                 100.000000  
0.125                     89.125000                  99.000000  
0.250                     88.260937                  98.012500  
0.375                     87.407676                  97.037344  
0.500                     86.565080                  96.074377  
...                             ...                        ...  
29.500                    23.596290                  24.110045  
29.625                    23.551336                  24.058670  
29.750                 

In [63]:
conds = {"Black": 1, "Green": 2, "Mint": 80, "Berries": 20}
ini_t = xr.DataArray(pd.Series(conds.values(), index=conds.keys(), name="t"))
ini_t = ini_t.rename({"dim_0": "teatype"})
ini_t

<xarray.DataArray 't' (teatype: 4)>
array([ 1,  2, 80, 20])
Coordinates:
  * teatype  (teatype) object 'Black' 'Green' 'Mint' 'Berries'

In [105]:
model_for_init_cond = pysd.load('/home/lionel/Projects/pysimgame/trials/subscripting_usage/teacup_subscript.py')

In [106]:
model_for_init_cond.set_initial_condition((0.0, {'Teacup Temperature': ini_t}))
# This does not work !!! # See below

In [107]:
model_for_init_cond.run(initial_condition='current')


FINAL TIME  INITIAL TIME  SAVEPER  TIME STEP  Characteristic Time  \
0.000           30           0.0    0.125      0.125                   10   
0.125           30           0.0    0.125      0.125                   10   
0.250           30           0.0    0.125      0.125                   10   
0.375           30           0.0    0.125      0.125                   10   
0.500           30           0.0    0.125      0.125                   10   
...            ...           ...      ...        ...                  ...   
29.500          30           0.0    0.125      0.125                   10   
29.625          30           0.0    0.125      0.125                   10   
29.750          30           0.0    0.125      0.125                   10   
29.875          30           0.0    0.125      0.125                   10   
30.000          30           0.0    0.125      0.125                   10   

        Heat Loss to Room[Mint]  Heat Loss to Room[Green]  \
0.000                 -1.900000                 -1.800000   
0.125                 -1.876250                 -1.777500   
0.250                 -1.852797                 -1.755281   
0.375                 -1.829637                 -1.733340   
0.500                 -1.806766                 -1.711673   
...                         ...                       ...   
29.500                -0.097614                 -0.092476   
29.625                -0.096393                 -0.091320   
29.750                -0.095188                 -0.090179   
29.875                -0.093999                 -0.089051   
30.000                -0.092824                 -0.087938   

        Heat Loss to Room[Berries]  Heat Loss to Room[Black]  \
0.000                     6.000000                       0.0   
0.125                     5.925000                       0.0   
0.250                     5.850938                       0.0   
0.375                     5.777801                       0.0   
0.500                     5.705578                       0.0   
...                            ...                       ...   
29.500                    0.308253                       0.0   
29.625                    0.304400                       0.0   
29.750                    0.300595                       0.0   
29.875                    0.296838                       0.0   
30.000                    0.293127                       0.0   

        Room Temperature  Teacup Temperature[Mint]  Teacup Temperature[Green]  \
0.000                 20                  1.000000                   2.000000   
0.125                 20                  1.237500                   2.225000   
0.250                 20                  1.472031                   2.447188   
0.375                 20                  1.703631                   2.666598   
0.500                 20                  1.932335                   2.883265   
...                  ...                       ...                        ...   
29.500                20                 19.023864                  19.075240   
29.625                20                 19.036066                  19.086799   
29.750                20                 19.048115                  19.098214   
29.875                20                 19.060014                  19.109487   
30.000                20                 19.071764                  19.120618   

        Teacup Temperature[Berries]  Teacup Temperature[Black]  
0.000                     80.000000                       20.0  
0.125                     79.250000                       20.0  
0.250                     78.509375                       20.0  
0.375                     77.778008                       20.0  
0.500                     77.055783                       20.0  
...                             ...                        ...  
29.500                    23.082534                       20.0  
29.625                    23.044002                       20.0  
29.750                 

In [86]:
model_for_init_cond = pysd.load('/home/lionel/Projects/pysimgame/trials/subscripting_usage/teacup_subscript_dataset.py')

In [88]:
df = model_for_init_cond.run()

In [92]:
%matplotlib qt
df.plot()

<AxesSubplot:>

In [109]:
_subscript_dict = {"teatype": ["Mint", "Green", "Berries", "Black"]}

initial_ds = xr.Dataset(
    {
        "Characteristic Time": (["teatype"], np.array([8, 8, 8, 8])),
        "Teacup Temperature": (["teatype"], np.array([65, 85, 95, 100])),
    },
    _subscript_dict,
)
model_for_init_cond = pysd.load('/home/lionel/Projects/pysimgame/trials/subscripting_usage/teacup_subscript_dataset.py')
model_for_init_cond.set_components(initial_ds)
model_for_init_cond.run(initial_condition='current')

/tmp/ipykernel_4423/18932166.py:11: UserWarning: Replacing the equation of stockTeacup Temperature with params
  model_for_init_cond.set_components( initial_ds)


FINAL TIME  INITIAL TIME  SAVEPER  TIME STEP  \
0.000           30             0    0.125      0.125   
0.125           30             0    0.125      0.125   
0.250           30             0    0.125      0.125   
0.375           30             0    0.125      0.125   
0.500           30             0    0.125      0.125   
...            ...           ...      ...        ...   
29.500          30             0    0.125      0.125   
29.625          30             0    0.125      0.125   
29.750          30             0    0.125      0.125   
29.875          30             0    0.125      0.125   
30.000          30             0    0.125      0.125   

        Characteristic Time[Mint]  Characteristic Time[Green]  \
0.000                         8.0                         8.0   
0.125                         8.0                         8.0   
0.250                         8.0                         8.0   
0.375                         8.0                         8.0   
0.500                         8.0                         8.0   
...                           ...                         ...   
29.500                        8.0                         8.0   
29.625                        8.0                         8.0   
29.750                        8.0                         8.0   
29.875                        8.0                         8.0   
30.000                        8.0                         8.0   

        Characteristic Time[Berries]  Characteristic Time[Black]  \
0.000                            8.0                         8.0   
0.125                            8.0                         8.0   
0.250                            8.0                         8.0   
0.375                            8.0                         8.0   
0.500                            8.0                         8.0   
...                              ...                         ...   
29.500                           8.0                         8.0   
29.625                           8.0                         8.0   
29.750                           8.0                         8.0   
29.875                           8.0                         8.0   
30.000                           8.0                         8.0   

        Heat Loss to Room[Mint]  Heat Loss to Room[Green]  \
0.000                     5.625                     8.125   
0.125                     5.625                     8.125   
0.250                     5.625                     8.125   
0.375                     5.625                     8.125   
0.500                     5.625                     8.125   
...                         ...                       ...   
29.500                    5.625                     8.125   
29.625                    5.625                     8.125   
29.750                    5.625                     8.125   
29.875                    5.625                     8.125   
30.000                    5.625                     8.125   

        Heat Loss to Room[Berries]  Heat Loss to Room[Black]  \
0.000                        9.375                      10.0   
0.125                        9.375                      10.0   
0.250                        9.375                      10.0   
0.375                        9.375                      10.0   
0.500                        9.375                      10.0   
...                            ...                       ...   
29.500                       9.375                      10.0   
29.625                       9.375                      10.0   
29.750                       9.375                      10.0   
29.875                       9.375                      10.0   
30.000                       9.375                      10.0   

        Room Temperature  Teacup Temperature[Mint]  Teacup Temperature[Green]  \
0.000                 20                      65.0                       85.0   
0.125                 20                      65.0                       

In [101]:
for key, val in initial_ds.items():
    print(key, val)

Teacup Temperature <xarray.DataArray 'Teacup Temperature' (teatype: 4)>
array([ 65,  85,  95, 100])
Coordinates:
  * teatype  (teatype) <U7 'Mint' 'Green' 'Berries' 'Black'
Characteristic Time <xarray.DataArray 'Characteristic Time' (teatype: 4)>
array([8, 8, 8, 8])
Coordinates:
  * teatype  (teatype) <U7 'Mint' 'Green' 'Berries' 'Black'
